CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255),
    celular VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP,
    data_inativacao TIMESTAMP,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT uk_usuario_celular UNIQUE (celular)
);

CREATE TABLE titulo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    valor NUMERIC(19, 2) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento TIMESTAMP,
    tipo VARCHAR(255) NOT NULL,
    id_usuario BIGINT NOT NULL,
    CONSTRAINT fk_titulo_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id),
    CONSTRAINT ck_titulo_tipo CHECK (tipo IN ('PAGAR', 'RECEBER'))
);

CREATE TABLE centro_de_custo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    observacao TEXT,
    id_usuario BIGINT NOT NULL,
    CONSTRAINT fk_centro_de_custo_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id)
);

CREATE TABLE titulo_centro_custo (
    id_titulo BIGINT NOT NULL,
    id_centro_custo BIGINT NOT NULL,
    CONSTRAINT pk_titulo_centro_custo PRIMARY KEY (id_titulo, id_centro_custo),
    CONSTRAINT fk_titulo_centro_custo_titulo FOREIGN KEY (id_titulo) REFERENCES titulo (id),
    CONSTRAINT fk_titulo_centro_custo_centro FOREIGN KEY (id_centro_custo) REFERENCES centro_de_custo (id)
);

CREATE INDEX idx_titulo_id_usuario ON titulo (id_usuario);
CREATE INDEX idx_centro_de_custo_id_usuario ON centro_de_custo (id_usuario);
CREATE INDEX idx_titulo_centro_custo_id_centro ON titulo_centro_custo (id_centro_custo);

