CREATE TABLE recuperacao_senha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    codigo VARCHAR(6) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL,
    data_expiracao TIMESTAMP NOT NULL,
    data_inativacao TIMESTAMP,
    data_utilizacao TIMESTAMP,
    CONSTRAINT fk_recuperacao_senha_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario (id)
);

CREATE INDEX idx_recuperacao_senha_id_usuario
    ON recuperacao_senha (id_usuario);

CREATE INDEX idx_recuperacao_senha_codigo
    ON recuperacao_senha (codigo);

CREATE INDEX idx_recuperacao_senha_ativo
    ON recuperacao_senha (ativo);
