ALTER TABLE titulo ADD COLUMN recorrencia VARCHAR(20);
ALTER TABLE titulo ADD COLUMN data_inicio DATE;
ALTER TABLE titulo ADD COLUMN data_fim DATE;
ALTER TABLE titulo ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE titulo ADD COLUMN criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE titulo ADD CONSTRAINT ck_titulo_recorrencia
    CHECK (recorrencia IS NULL
    OR recorrencia IN ('SEMANAL','MENSAL','BIMESTRAL','TRIMESTRAL','SEMESTRAL','ANUAL'));


UPDATE titulo SET data_inicio = data_vencimento WHERE data_inicio IS NULL;

ALTER TABLE titulo ALTER COLUMN data_inicio SET NOT NULL;


CREATE TABLE faturamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_titulo BIGINT NOT NULL,
    data_vencimento DATE NOT NULL,
    valor NUMERIC(19, 2) NOT NULL,
    data_pagamento TIMESTAMP,
    observacao VARCHAR(500),
    CONSTRAINT fk_faturamento_titulo FOREIGN KEY (id_titulo)
        REFERENCES titulo (id) ON DELETE CASCADE
);

CREATE INDEX idx_faturamento_id_titulo ON faturamento (id_titulo);
CREATE INDEX idx_faturamento_data_vencimento ON faturamento (data_vencimento);

INSERT INTO faturamento (id_titulo, data_vencimento, valor, data_pagamento)
SELECT id, data_vencimento, valor, data_pagamento FROM titulo;
-- cada Titulo legado gera 1 Faturamento (preserva histórico de pagamento)
